build:
  stage: build
  image: docker:24.0.7-cli
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker compose build
  artifacts:
    paths:
      - build/*.jar